<?php

Class Welcome extends Welcome_Controller {
    
    function __construct()
    {   
        parent::__construct();
        
        // loader::helper('ob/request'); 

        loader::model('app/test_model');
    }         
    
    public function index()
    {   
        view_var('title', 'Welcome to Obullo Framework !');
       
        // $request = request('get', 'api/test/method.ajax/1/');
        // echo $request->exec()->response();
        
        /*
        $request = request('get', 'api/test/method.ajax');
        echo $request->exec()->response();
        */
        
       
        echo '<a href="javascript:void(0);" onclick="send_ajax();">Ajax Request</a>';
                       
        $data['var'] = 'and generated by ';
       
          
        view_var('body', view('view_welcome', $data));
        view_layout('layout_welcome'); 
    }
    
    function test($arg1 = '', $arg2 = '')
    {
        echo 'hmvc-cmd-test: '.$arg1 .' -- '.$arg2;
    }
    
    
    function task()
    {
        loader::helper('ob/task');
        
        task_run('welcome/hello/index', true);
    }
    
}

/* End of file start.php */
/* Location: .modules/welcome/controllers/welcome.php */