<?php

Class Welcome extends Welcome_controller {
    
    function __construct()
    {   
        parent::__construct();
        loader::base_helper('hmvc');
    }           
    
    public function index($hello = '')
    {                
        // $this->doly->var = 'welcome controller';
        
        // echo $this->uri->uri_string;
        
        $this->hello = 'blabla';
        $hmvc = hmvc_request('GET', 'api/v3?query=SELECT+%%%from&bool=true', array('last' => 'me'), 0);
        $hmvc->set_server('USER_AGENT', 'Hmvc class');
        $result = $hmvc->exec()->response();
        echo json_decode($result);
        //  print_r($_SERVER);        

        echo '<br />';
    
        $hmvc = hmvc_request('GET', 'api?query=SELECT+%%%from&bool=true', array('last' => 'me'));
        $result = $hmvc->exec()->response();
        echo json_decode($result);
        

        
        // echo $this->doly->var;
        
        view_var('title', 'Welcome to Obullo Framework !');
        
        $data['var'] = 'This page generated by ';
        
        view_var('body', view('view_welcome', $data));
        view_temp('layout_base'); 
    }
    
    
    function _test()
    {
        echo 'test function works fine !';
    }
    
}

/* End of file start.php */
/* Location: .modules/welcome/controllers/welcome.php */