<?php
view_var('meta', meta('keywords', 'obullo, validation model, vm, validation in model'));
view_var('head', css('.input-error { color: #DF4545; }', 'embed'));
?>

<!-- body content -->
<h1>Welcome to Obullo Validation Model !</h1> 

<div style="padding: 10px 10px 10px 0;"><? echo anchor('/test/vm/start', 'Validation Model (No Ajax)'); ?> | <? echo anchor('/test/vm/start/ajax_example', 'Validation Model (VM) with Ajax'); ?></div>

<? echo sess_flash('msg', '<div style="padding:10px;">' ,'</div>')?>

<? echo form_open('/test/vm/start/do_post', array('method' => 'POST', 'class' => 'no-ajax'));?>
<table>
    
    <tr>
        <td width="35%"><b>Username</b></td>
        <td>
        <? echo form_error('username', '<div class="input-error">', '</div>'); ?>
        <? echo form_input('username', '', " id='username' ");?></td>
    </tr>
    
    <tr>
        <td><b>Email</b></td>
        <td>
        <? echo form_error('email', '<div class="input-error">', '</div>'); ?>
        <? echo form_input('email', '', " id='email' ");?></td>
    </tr>
    
    <tr>
        <td></td>
        <td><? echo form_submit('do_post', 'Do Post');?><font size="1"> * Please do post with blank fields and see the errors.</font></td>
    </tr>
    
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    
    <tr>
        <td><b>Code</b></td>
        <td>
<pre>
$user = new User();
$user->username = i_get_post('username');
$user->email    = i_get_post('email');

if($user->save())
{
    if($this->uri->extension() == 'json')  // Ajax support
    {
        echo form_json_success('Success !');
        return;
    }

    sess_set_flash('msg', 'Data Saved !');
    redirect('/test/vm/start/index');
} 
else
{
    if($this->uri->extension() == 'json') // Ajax support
    {
        echo form_json_error($user);
        return;
    }

    $data['user'] = $user;

    view_var('body', view('view_vm', $data));
    view_layout('layout_vm'); 
}</pre></td>
    </tr>
    
    
    <tr>
        <td colspan="2">Test Results</td>
    </tr>
    <tr>
        <td><b>form_error('username');</b></td>
        <td><pre><? echo form_error('username'); ?></pre></td>
    </tr>
    
    <tr>
        <td><b>validation_errors();</b></td>
        <td><pre><? echo validation_errors(' | ', ' | '); ?></pre></td>
    </tr>
    
    <? if(isset($user)) { ?>
    
    <tr>
        <td><b>print_r($user->errors());</b></td>
        <td><pre><? print_r($user->errors()); ?></pre></td>
    </tr>
    
    <tr>
        <td><b>print_r($user->errors());</b></td>
        <td><pre><? print_r($user->errors); ?></pre></td>
    </tr>
    
    <tr>
        <td><b>print_r($user->values());</b></td>
        <td><pre><? print_r($user->values()); ?></pre></td>
    </tr>
    
    <tr>
        <td><b>print_r($user->values);</b></td>
        <td><pre><? print_r($user->values); ?></pre></td>
    </tr>
    
    <? } ?>
        
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    
</table>
     
<? echo form_close(); ?>

<p>
<?php echo br(); ?>Page rendered in {elapsed_time} seconds 

<?php if(function_exists('memory_get_usage')) {?> using {memory_usage} of memory <?php } ?> generated by 
<?php
// calling images from welcome module !
echo img('../welcome/gif/obullo.gif', ' border="0" '); ?>
</p>

<?php echo br(); ?>
<!-- body content -->
