<?php

Class Start extends Welcome_Controller {
    
    function __construct()
    {   
        parent::__construct();
        
        loader::model('user', false);
    }         
    
    public function index()
    { 
        $user = new User();
        $user->username = 'develturk4'; // 'develturk <script>sd</script>';
        $user->email    = 'cccceguvenc@gmail.com';
        $user->save_join('user_address', 'user_id = id');
        $user->address_line = 'test2 ... ';
        $user->save();
        
        /*
        $adr = new User_Address();
        $adr->user_id = $user->save();
        $adr->address_line = 'test ... ';
        $adr->save_all();
        */
        
        // echo form_error('id');
        // echo form_error('username');
        // echo form_validate_errors();
        
        //------------------- DELETE ---------------------//
        /*
        if($user->delete(5)) // $user->delete_all('user_address, user_logs'); // delete from all related tables.
        {
            echo 'ok';   
        }
        */
        // echo $user->last_query();

        print_r($user->errors);
        print_r($user->values);
        
        
        // $user->get()->fetch_all();
        
        // echo $user->get(10, 20)->last_query();
        
        view_var('title', 'Welcome to Obullo Framework !');
                       
        $data['var'] = 'and generated by ';  
        view_var('body', view('view_welcome', $data));
        view_layout('layout_welcome'); 
    }
}

/* End of file start.php */
/* Location: .modules/welcome/controllers/welcome.php */
