<?php

Class Start extends Welcome_Controller {
    
    function __construct()
    {   
        parent::__construct();
        
        loader::model('user', false);
    }         
    
    public function index()
    { 
        $user = new User();
        $user->username = 'develturk2'; // 'develturk <script>sd</script>';
        $user->id = '3';  // if not isset id do validation else not. good idea.
        $user->email    = 'aeguvenc@gmail.com';
        
        // loader::helper('ob/security');
        // echo xss_clean('develturk <script>sd</script>');
        /*
        if($user->save())
        {
            print_r($user->errors);
            print_r($user->values);
            return;
        }
*/
        // echo form_error('id');
        // echo form_error('username');
        // echo form_validate_errors();
        
        // $user->where();
        // $user->where_in('id', array('1', '3'));
        if($user->delete()) // $user->delete_all('user_address, user_logs'); // delete from all related tables.
        {
            
        }
        
        echo $user->last_query();
        /*
        $ua = new User_Address();
        $ua->user_id = $user->id;
        $ua->delete();
        */
        print_r($user->errors);
        print_r($user->values);
        
        return;
        

        
        // $user->find()->fetch_all();
        
        echo $user->find(10, 20)->last_query();
                
        view_var('title', 'Welcome to Obullo Framework !');
                       
        $data['var'] = 'and generated by ';  
        view_var('body', view('view_welcome', $data));
        view_layout('layout_welcome'); 
    }
}

/* End of file start.php */
/* Location: .modules/welcome/controllers/welcome.php */
